kafkaSelector:
  type: file
  path: gateway-core/config/kafka.config
interceptors:
  - name: loggingInterceptor
    pluginClass: io.conduktor.example.loggerinterceptor.LoggerInterceptorPlugin
    timeoutMs: 30000 #optional. default timeoutMs = request.timeout.ms of kafka
    priority: 100
    config:
      - key: "loggingStyle"
        value: "obiWan"