on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      from:
        type: string
        description: 'Tag or sha to publish'
        required: true

name: Publish
run-name: Publish from ${{inputs.from}}

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.from}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github

      - name: Build with Maven
        run: mvn -B deploy --file pom.xml -pl '!logger-interceptor'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}